ファイル作成
JuN-front/Junfuku-frontend-basic-last-assignment pull request #14
Opened 2023-05-06 03:58 UTC by JuN-front

## セルフチェック
- [〇] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [〇] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [〇] 記述の重複はないか

2023-05-08 05:31 UTC, AyumuTaoka commented on src/components/organisms/top/top.scss
> +        line-height: 52px;
合計のwidthが82pxなのでline-heightを41pxにしてみて合計のwidthが82pxになるか試してみてください

2023-05-08 05:31 UTC, AyumuTaoka commented on src/components/organisms/top/top.scss
> +          line-height: 29px;
こちらは合計50pxなので25pxで試してみてください

2023-05-08 05:38 UTC, AyumuTaoka commented on src/components/organisms/top/top.html
> +  </div>
ここは過去に作った.messageを使うと良いところです
```suggestion
  <div class="advertisement">
  <div class="message">
    <h2>
      カフェで読書＆コワーキング。快適のフロアスペース空間。
    </h2>
    <p>
      カフェエリアでコーヒーを注文し、ブックエリアでお好みの本を選び、コワーキングスペースでコーヒーと共に読書を楽しむ。<br />
      学校・仕事帰りに、平日の日中に、休日にゆっくり...さまざまなライフスタイルに合わせてご利用いただける多彩なプランをご用意しております。
    </p>
</div>
  </div>
```

2023-05-10 11:53 UTC, AyumuTaoka commented
molecules-messageの修正なのですが、figmaを見た感じ以下のpaddingの方が適切だと思います
padding: 52px 20px; または padding: 32px 20px;

2023-05-10 12:00 UTC, AyumuTaoka commented
また、molecules-messageの外側にもpaddingがついているので
<img width="1512" alt="スクリーンショット 2023-05-10 20 57 31" src="https://github.com/JuN-front/Junfuku-frontend-basic-last-assignment/assets/104242534/905d8b82-e912-4b60-aae6-52b7209ea920">
ここの修正もお願いします

2023-05-12 11:56 UTC, AyumuTaoka commented on src/components/organisms/top/top.scss
> +    width: 992px;
widthをつけることで以下の画像のようになってしまっているのでwidthの削除お願いします
<img width="1157" alt="スクリーンショット 2023-05-12 20 52 32" src="https://github.com/JuN-front/Junfuku-frontend-basic-last-assignment/assets/104242534/ac478153-79b6-4bf5-b340-026604c53abe">

2023-05-12 11:56 UTC, AyumuTaoka commented on src/components/organisms/top/top.scss
> +    }
messageについてですがmolecules/messageの値が違うようなのでそこのファイル内で直接widthを変更したほうが適切です。
また、今回の変更につきましては小さな変更なのでこのブランチ内で変更しても問題ないと思います

2023-05-12 12:02 UTC, AyumuTaoka commented on src/components/organisms/top/top.scss
> +    background-color: $black;
ここはmolecules/messageにはない記述なので残しておいてください

2023-05-12 12:08 UTC, AyumuTaoka commented on src/components/organisms/top/top.scss
> +  .message {
paddingについてですが、.advertisementに対して指定するとうまくいくと思います。
値については確認お願いします
```suggestion
.advertisement {
  background-color: $black;
  padding: md, lgでそれぞれ別のやつつける
  .message {
```

2023-05-13 04:57 UTC, AyumuTaoka commented on src/components/organisms/top/top.scss
> +    }
このpaddingはmolecules/messageで指定されているので以下の画像を参考にpaddingの修正お願いします
<img width="1440" alt="スクリーンショット 2023-05-13 13 56 07" src="https://github.com/JuN-front/Junfuku-frontend-basic-last-assignment/assets/104242534/a80a26fe-b108-456a-8299-46f2b965b353">
<img width="1440" alt="スクリーンショット 2023-05-13 13 55 37" src="https://github.com/JuN-front/Junfuku-frontend-basic-last-assignment/assets/104242534/c0c3a4c6-52ea-4128-8fde-c9a6027d036a">

2023-05-16 10:22 UTC, AyumuTaoka commented on src/components/organisms/top/top.scss
> +  margin-bottom: 30px;
このmargin-bottomをfigmaで確認できないのですが、figmaでどこを参考にしたか画像付きで載せてもらえると助かります。もし必要がなさそうであれば決しておいてください。

2023-05-16 10:31 UTC, AyumuTaoka commented
今回修正していただいた箇所なのですがpaddingの省略記法として元のままの書き方の方が好ましいので元に戻しておいてください。
<img width="1271" alt="スクリーンショット 2023-05-16 19 29 10" src="https://github.com/JuN-front/Junfuku-frontend-basic-last-assignment/assets/104242534/35cc63e0-42fa-4a1b-9030-49b51484e004">

2023-05-16 10:33 UTC, AyumuTaoka commented
こちら確認お願いします
https://github.com/JuN-front/Junfuku-frontend-basic-last-assignment/pull/14#discussion_r1194948993

2023-05-17 03:39 UTC, higashiji2000 requested changes
いい感じです！
コミットメッセージをコミット内容に準ずる内容にすると自分にも他人にもわかりやすくなるかと思います。
[こちら](https://www.praha-inc.com/lab/posts/commit-message)の記事参考になると思うので時間あるときに読んでみてください！

2023-05-17 03:39 UTC, higashiji2000 commented on src/components/organisms/top/top.scss
> +  }
```suggestion
.container {
  margin: 0 auto;

```

<img width="1512" alt="image" src="https://github.com/JuN-front/Junfuku-frontend-basic-last-assignment/assets/83479175/19296e88-744a-40c4-9933-7897e7f91c00">
画面の幅が狭いときにmessageがコンテナを貫通しているので修正お願いします！

widthの指定自体なくすという対応で問題ないかと思います。

2023-05-17 03:39 UTC, higashiji2000 commented on src/components/organisms/top/top.html
> +      <h2 class="advertisement">
```suggestion
      <h2>
```
messageの中の `.advertisement` には特にスタイル当ててないと思うので、特別な意図が無い限り混乱を防ぐために削除してしまうのが望ましいです。

2023-05-18 02:43 UTC, higashiji2000 approved these changes
LGTM🛸

2023-05-18 02:44 UTC, merged