Orgas/Footer
JuN-front/Junfuku-frontend-basic-last-assignment pull request #18
Opened 2023-06-10 12:43 UTC by JuN-front

## セルフチェック
- [〇] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [〇] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [〇] 記述の重複はないか

2023-06-12 13:56 UTC, AyumuTaoka commented on src/components/organisms/footer/footer.scss
> +      line-height: 28px;
以下を追加しFigma通りの実装になっているか確認してください
```suggestion
      line-height: 28px;
      margin-bottom: 20px;
```

2023-06-12 13:56 UTC, AyumuTaoka commented on src/components/organisms/footer/footer.scss
> +        }
font-sizeが違うので指定お願いします

2023-06-12 13:56 UTC, AyumuTaoka commented on src/components/organisms/footer/footer.html
> +    </small>
ここline-heightの指定お願いします

2023-06-15 09:58 UTC, AyumuTaoka commented on src/components/organisms/footer/footer.scss
> +      border-left: 1px solid;
link間のborderの高さが20pxなのでここでheightを指定するとうまくいくと思います
```suggestion
    li {
      list-style: none;
      padding: 0 8px;
      border-left: 1px solid;
      height: 20px;
```

2023-06-17 01:52 UTC, higashiji2000 requested changes
画面幅が小さいときのメニューの周りだけ修正お願いします！

2023-06-17 01:52 UTC, higashiji2000 commented on src/components/organisms/footer/footer.scss
> +      height: 20px;
```suggestion
      border-left: 1px solid;
      height: 20px;
```
`box-sizing: border-box;` の状態でpaddingとheightを両方指定すると、paddingも含めて20pxにしようとします。
そのため、現状テキストのための余白が 12px しか残されておらず、文字がpaddingの領域にはみ出してしまっています。

paddingで余白を調整せず、 `gap` を使うようにしましょう。

参考：https://developer.mozilla.org/ja/docs/Web/CSS/box-sizing
![image](https://github.com/JuN-front/Junfuku-frontend-basic-last-assignment/assets/83479175/8879a676-bf67-418f-a51c-d1896b5102f6)

2023-06-17 01:52 UTC, higashiji2000 commented on src/components/organisms/footer/footer.scss
> +    border-top: 1px solid;
```suggestion
  .link {
    background-color: $white_smoke;
    padding-left: 0;
    display: flex;
    justify-content: center;
    margin: 0;
    padding: 16px;
    border-top: 1px solid;
    row-gap: 8px;
```
display: flex や grid を設定している場合、要素同士の間隔は `gap` で調整するのが便利です。
（row-gapは縦の間隔のみを設定するプロパティです）
参考：https://developer.mozilla.org/ja/docs/Web/CSS/gap

2023-06-17 01:52 UTC, higashiji2000 commented on src/components/organisms/footer/footer.scss
> +      }
gapで間隔を調整するとこのあたりは不要になります。

2023-06-17 02:07 UTC, higashiji2000 requested changes
![image](https://github.com/JuN-front/Junfuku-frontend-basic-last-assignment/assets/83479175/1d212a01-b8c0-469a-a16a-d872206bcd69)
画面幅が大きいときにくずれてしまっているので修正お願いします。
これも gap ( column-gap )を利用するのがいいかなと思います。

2023-06-17 03:32 UTC, higashiji2000 requested changes

2023-06-17 03:32 UTC, higashiji2000 commented on src/components/organisms/footer/footer.scss
> +        &:hover {
```suggestion
        text-decoration: none;
        color: $black;
        transition: 0.2s ease;
        font-size: $fontsize-s;
        &:hover {
```
lg 以上のときフォントサイズが少し大きいので、このように追加お願いします。

2023-06-17 03:35 UTC, higashiji2000 commented on src/components/organisms/footer/footer.scss
> +    }
```suggestion
    .link {
      display: grid;
      grid-template-columns: 1fr 1fr;
      text-align: left;
      flex-wrap: wrap;
      gap: 8px;

      li {
        border-left: 0 solid;
        padding: 0px;

        a {
          line-height: 20px;
          font-size: $fontsize-s;
        }
      }
    }
```

こうするとより簡潔に書けます

2023-06-17 03:43 UTC, higashiji2000 approved these changes
LGTM🇹🇼

2023-06-17 03:46 UTC, merged