Molecules/Message プルリクエスト
JuN-front/Junfuku-frontend-basic-last-assignment pull request #4
Opened 2023-03-04 13:35 UTC by JuN-front

## セルフチェック
- [〇] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [〇] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [〇] 記述の重複はないか

2023-03-05 14:43 UTC, renyagi commented on src/components/molecules/message/message.scss
> +        line-height: 54px;
値自体は間違っていないのですが、line-heightに対しては単位を付けないほうが良いと思います。
以下のサイトを参考にかき方を変えてみてください。
参考
https://developer.mozilla.org/ja/docs/Web/CSS/line-height

2023-03-05 14:43 UTC, renyagi commented on src/components/molecules/message/message.scss
> +        font-family: $fontfamily-mincho;
$fontfamily-gothicな気がします

2023-03-05 14:45 UTC, renyagi commented
コミットする際に＃だけでなく、簡単な記述があるとよいですね。
例えば、message.html完成みたいな感じです。

2023-03-06 03:31 UTC, ssshun3 commented
いい感じです！

コードの行の隙間やインデントが少し気になるのでprettierが効いているか[こちら](https://zenn.dev/k_kazukiiiiii/articles/670ebae0005872)を参考にして確認してみてください。

また、コミットメッセージ「＃」では何を変更したかわからないので、変更した点を文章にしてください。
[こちら](https://playground.wraptas.site/d89ccb4cd1ec42f6b599e44e175e0d6f)を参考にしてください。

2023-03-06 03:31 UTC, ssshun3 commented on src/components/molecules/message/message.html
> +    <h1>タイトルテキスト</h1>
h1タグはサイトの中で１番大きな見出しに使うのですが今回のパーツのmessageは他のパーツ(organisms)で使いまわします。そのためh1タグは適していないのでh2などを使用してください。

2023-03-06 03:31 UTC, ssshun3 commented on src/components/molecules/message/message.scss
> +        line-height: 54;
line-heightの単位なしの値の仕様として、この値に要素のフォントサイズを掛けたものがline-heightになるので、今回の場合line-heightは
54×36px=1944pxとなります。単位なしを利用する場合はこの仕様を考慮しながら使用してください。
また、単位なしと単位ありが混在している(pタグやメディアクエリの中)ので統一してください
今回の場合は以下のようになると思います。
```suggestion
        line-height: 1.5;
```

2023-03-06 03:33 UTC, ssshun3 commented on src/components/molecules/message/message.scss
> +        font-family: $fontfamily-gothic;
デフォルトで$fontfamily-gothicのため指定しなくて大丈夫です

2023-03-07 04:29 UTC, ssshun3 commented
[こちら](https://github.com/JuN-front/Junfuku-frontend-basic-last-assignment/pull/4#issuecomment-1455387071)の確認だけお願いします。

2023-03-08 15:02 UTC, higashiji2000 requested changes
コードとしては問題ないです！
コミットメッセージもいい感じですね 👍

2023-03-08 15:02 UTC, higashiji2000 commented on src/components/molecules/message/message.html
> +<div class="Message">
```suggestion
<div class="message">
```
サイト制作課題では、CSSのクラス名は基本的にケバブケースで書いていきましょう！
参考：https://qiita.com/ybiquitous/items/75288bacb596a82a2805

2023-03-08 15:02 UTC, higashiji2000 commented on src/components/molecules/message/message.scss
> +.Message{
```suggestion
.message{
```

2023-03-11 02:24 UTC, higashiji2000 approved these changes

2023-03-13 00:20 UTC, merged